---
galaxy_info:
    author: "Sam Doran, Josh Springer, Daniel Shepherd, Bas Meijeri, James Cassell, Mike Renfro, DFed, George Nalen"
    description: "Apply the DISA RHEL 7 STIG"
    company: "MindPoint Group"
    license: MIT
    min_ansible_version: 2.8.0

    platforms:
        - name: EL
          versions:
              - 8

    galaxy_tags:
        - system
        - security
        - stig
        - hardening

dependencies: []
