---
- name: run another report
  shell: "oscap xccdf eval \
      --datastream-id scap_org.open-scap_datastream_from_xccdf_ssg-rhel8-xccdf-1.2.xml \
      --xccdf-id scap_org.open-scap_cref_ssg-rhel8-xccdf-1.2.xml \
      --profile {{ rhel8cis_scap_profile }} \
      --oval-results \
      --results {{ rhel8cis_report_dir }}/{{ ansible_hostname }}-oscap-postreport.xml \
      --report {{ rhel8cis_report_dir }}/{{ ansible_hostname }}-oscap-postreport.html \
      --fetch-remote-resources {{ distrocontent }}"
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Get the second scan result from the XML after
  slurp:
      path: "{{ rhel8cis_report_dir }}/{{ ansible_hostname }}-oscap-postreport.xml"
  register: rhel8cis_postreport

- name: let's set a dict of the second result
  set_fact:
      rhel8cis_postscanresults: "{{ rhel8cis_postreport['content'] | b64decode | xml2json }}"
  changed_when: true
  notify: postreport score
